# Generated by Django 5.2.17 on 2026-09-28 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0002_ctmstransaction_assigned_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtmsDisplayConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arta_video_url', models.TextField(blank=True, default='', help_text='YouTube or direct MP4 video URL for TV display')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_config', to='ctms.csmoffice')),
            ],
            options={
                'verbose_name': 'CTMS Display Config',
                'verbose_name_plural': 'CTMS Display Configs',
                'db_table': 'ctms_display_config',
            },
        ),
    ]
