# Generated by Django 5.2.17 on 2026-09-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0003_ctmsdisplayconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctmsdisplayconfig',
            name='video_file',
            field=models.FileField(blank=True, help_text='Uploaded video file for TV display', null=True, upload_to='arta_videos/'),
        ),
    ]
