# Generated by Django 5.2.17 on 2026-09-29 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0004_ctmsdisplayconfig_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsmDivision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'CSM Division',
                'verbose_name_plural': 'CSM Divisions',
                'db_table': 'csm_division',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtmsEmployee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('divisions', models.ManyToManyField(blank=True, db_table='ctms_employee_divisions', related_name='employees', to='ctms.csmdivision')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='ctms.csmoffice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CTMS Employee',
                'verbose_name_plural': 'CTMS Employees',
                'db_table': 'ctms_employee',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
