# Generated by Django 5.2.17 on 2026-09-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0005_csmdivision_ctmsemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctmsemployee',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Requires password change on first login or after reset'),
        ),
    ]
