# Generated by Django 5.2.17 on 2026-09-29 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0007_ctmsemployee_is_active_alter_ctmsemployee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DolePersonnel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('divisions', models.ManyToManyField(blank=True, db_table='ctms_dole_personnel_divisions', related_name='dole_personnel', to='ctms.csmdivision')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dole_personnel', to='ctms.csmoffice')),
            ],
            options={
                'verbose_name': 'DOLE Personnel',
                'verbose_name_plural': 'DOLE Personnel',
                'db_table': 'ctms_dole_personnel',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CtmsStaffDivision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_division_assignments', to='ctms.csmdivision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_divisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CTMS Staff Division',
                'verbose_name_plural': 'CTMS Staff Divisions',
                'db_table': 'ctms_staff_division',
                'unique_together': {('user', 'division')},
            },
        ),
    ]
