# Generated by Django 5.2.17 on 2026-09-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0008_dolepersonnel_ctmsstaffdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctmstransaction',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Serving'), ('pending', 'Pending'), ('done', 'Done'), ('no_show', 'No-show'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=12),
        ),
    ]
