# Generated by Django 5.2.17 on 2026-09-30 09:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0009_alter_ctmstransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtmsAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_username', models.CharField(db_index=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(db_index=True, help_text='e.g. LOGIN, CALL_CLIENT, MARK_DONE, CREATE_USER, etc.', max_length=50)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('queue', 'Queue & Dispatch'), ('user', 'User Management'), ('personnel', 'Personnel Directory'), ('config', 'Configuration')], db_index=True, default='queue', max_length=50)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('target_repr', models.CharField(blank=True, default='', max_length=255)),
                ('office_name', models.CharField(blank=True, default='', max_length=200)),
                ('division_name', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ctms.csmoffice')),
            ],
            options={
                'verbose_name': 'CTMS Audit Log',
                'verbose_name_plural': 'CTMS Audit Logs',
                'db_table': 'ctms_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='ctms_audit__timesta_d507ec_idx'), models.Index(fields=['category', '-timestamp'], name='ctms_audit__categor_852e1e_idx'), models.Index(fields=['actor_username', '-timestamp'], name='ctms_audit__actor_u_d0f400_idx'), models.Index(fields=['office', '-timestamp'], name='ctms_audit__office__e0f8b0_idx')],
            },
        ),
    ]
