# Generated by Django 5.2.17 on 2026-10-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0010_ctmsauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctmstransaction',
            name='group_member_names',
            field=models.JSONField(blank=True, default=None, help_text="List of individual member names for group registrations, e.g. ['Juan', 'Maria', ...]", null=True),
        ),
    ]
