# Generated by Django 5.2.17 on 2026-10-05 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0011_add_group_member_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtmsServiceDefaultOfficer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('officer_name', models.CharField(help_text='Full name of the default officer', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_default_officers', to='ctms.csmoffice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_officers', to='ctms.csmservice')),
            ],
            options={
                'verbose_name': 'CTMS Service Default Officer',
                'verbose_name_plural': 'CTMS Service Default Officers',
                'db_table': 'ctms_service_default_officer',
                'unique_together': {('office', 'service')},
            },
        ),
    ]
