# Generated by Django 5.2.17 on 2026-10-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0012_add_service_default_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolepersonnel',
            name='services',
            field=models.ManyToManyField(blank=True, db_table='ctms_dole_personnel_services', related_name='assigned_personnel', to='ctms.csmservice'),
        ),
    ]
