# Generated by Django 5.2.17 on 2026-10-06 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0013_dolepersonnel_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dolepersonnel',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User login account linked to this personnel record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dole_personnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CtmsNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(default='ASSIGNMENT', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('queue_no', models.CharField(blank=True, default='', max_length=50)),
                ('service_name', models.CharField(blank=True, default='', max_length=200)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctms_notifications', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ctms.ctmstransaction')),
            ],
            options={
                'verbose_name': 'CTMS Notification',
                'verbose_name_plural': 'CTMS Notifications',
                'db_table': 'ctms_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='ctms_notifi_recipie_b150e6_idx')],
            },
        ),
    ]
