# Generated by Django 5.2.17 on 2026-10-06 06:52

from django.db import migrations, models


def backfill_started_at(apps, schema_editor):
    CtmsTransaction = apps.get_model('ctms', 'CtmsTransaction')
    CtmsTransaction.objects.filter(started_at__isnull=True, called_at__isnull=False).update(
        started_at=models.F('called_at')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0014_dolepersonnel_user_ctmsnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctmstransaction',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when transaction began serving', null=True),
        ),
        migrations.AlterField(
            model_name='ctmstransaction',
            name='done_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when transaction was completed', null=True),
        ),
        migrations.RunPython(backfill_started_at, migrations.RunPython.noop),
    ]
