# Generated by Django 5.2.17 on 2026-10-06 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0015_ctmstransaction_started_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtmsOfficeQrConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_qr_enabled', models.BooleanField(default=True, help_text='Enable or disable client QR check-in / registration')),
                ('disabled_message', models.CharField(blank=True, default='Online registration is currently closed beyond office hours. Please visit us during regular office hours (Monday to Friday, 8:00 AM - 5:00 PM).', help_text='Custom notice shown to clients when QR registration is closed', max_length=255)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disabled_qr_offices', to=settings.AUTH_USER_MODEL)),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_config', to='ctms.csmoffice')),
            ],
            options={
                'verbose_name': 'CTMS Office QR Config',
                'verbose_name_plural': 'CTMS Office QR Configs',
                'db_table': 'ctms_office_qr_config',
            },
        ),
    ]
