# Generated by Django 5.2.17 on 2026-10-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0016_ctmsofficeqrconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DolePosition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('is_custom', models.BooleanField(default=True, help_text='True if created dynamically by administrator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DOLE Position',
                'verbose_name_plural': 'DOLE Positions',
                'db_table': 'ctms_dole_position',
                'ordering': ['title'],
            },
        ),
    ]
